- SemSeg Pipeline (data.py): https://github.com/HasnainRaz/SemSegPipeline
- Semantic Segmentation and the Dataset (prepare dataset): https://d2l.ai/chapter_computer-vision/semantic-segmentation-and-dataset.html
- PLC segmentation (custom callback) : https://github.com/ika-rwth-aachen/PCLSegmentation/blob/main/pcl_segmentation/utils/callbacks.py
- Human Image Segmentation (data and application ) : https://github.com/nikhilroxtomar/Human-Image-Segmentation-with-DeepLabV3Plus-in-TensorFlow
- Deep Resnet and Resnet++ (pytorch) : https://github.com/rishikksh20/ResUnet
- Deep Resnet and Resnet++ (original repo and tf) : https://github.com/DebeshJha/ResUNetPlusPlus
- Loss functions for image segmentation : https://github.com/JunMa11/SegLoss
- Albumentations with tf.data : https://colab.research.google.com/drive/1uUH-asz3CFxlvld8uGx-m3crr4Iepp3u#scrollTo=LWO057_PshWr
- DeepLabv3 with (reference_repo) : https://github.com/lattice-ai/DeepLabV3-Plus
- tf-segmentation-segmentation (reference_repo) : https://github.com/baudcode/tf-semantic-segmentation/tree/feature/line-detection/tf_semantic_segmentation

In [1]:
%load_ext autoreload
%autoreload 2


from tensorflow import keras
from tensorflow.keras import initializers
from tensorflow.keras.layers import Conv2D,Conv1D
import numpy as np
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Layer
from tensorflow.keras.losses import Loss
from tensorflow.keras import Model
from tensorflow.keras import initializers
import tensorflow as tf


from tf_seg.utils import TensorLike, Tensor, FloatTensorLike,AcceptableDTypes

2022-10-03 09:31:17.655579: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-03 09:31:17.873256: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-10-03 09:31:17.927189: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-03 09:31:17.927222: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if yo

In [2]:
from tf_seg.models import resunet_pp

### Model

In [4]:
resunet_pp.ResUnetPlusPlus().build_model()

2022-10-03 09:31:36.634630: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-10-03 09:31:36.634706: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (yesilyurt): /proc/driver/nvidia/version does not exist
2022-10-03 09:31:36.636245: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
model = resunet_pp.ResUnetPlusPlus().build_model()


In [6]:
model.summary()


Model: "ResUnet++"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 256, 256, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv2d_41 (Conv2D)             (None, 256, 256, 16  448         ['input_2[0][0]']                
                                )                                                                 
                                                                                                  
 batch_normalization_37 (BatchN  (None, 256, 256, 16  64         ['conv2d_41[0][0]']              
 ormalization)                  )                                                         

In [7]:
model._attention_block(np.ones((1, 64, 64, 3)), np.ones((1, 32, 32, 15)))


AttributeError: 'Functional' object has no attribute '_attention_block'

In [8]:
model2 = resunet_pp.ResUnetPlusPlus()

In [9]:
model2.build_model()

### Layer

In [24]:
class ResidualLayer(Layer):
    def __init__(self,n_filter,activation='relu',kernel_size=3,name="residual",**kwargs):
        super().__init__(name=name)
        assert n_filter is not None ,'n_filter must be specified'

        self.activation_name = activation
        self.n_filter = n_filter
        self.kernel_size = kernel_size

       

    def build(self,input_shape):
        self.activation = keras.layers.Activation(self.activation_name)
        
        self.conv1 = Conv2D(filters=self.n_filter, kernel_size=self.kernel_size, padding="same",kernel_initializer=initializers.Ones())
        self.batch_norm1 = keras.layers.BatchNormalization()
        
        self.conv2 = Conv2D(filters=self.n_filter, kernel_size=self.kernel_size,padding="same",kernel_initializer=initializers.Ones())
        self.batch_norm2 = keras.layers.BatchNormalization()
        
        self.conv_skip = Conv2D(filters=self.n_filter, kernel_size=(1, 1), padding="same",kernel_initializer=initializers.Ones())
        self.batch_norm_skip = keras.layers.BatchNormalization()
        
        self.add = keras.layers.Add()


    def call(self,inputs):
        
        x = self.batch_norm1(inputs)
        x = self.activation(x)
        x = self.conv1(x)

        x = self.batch_norm2(x)
        x = self.activation(x)
        x = self.conv2(x)
        
        x_i = self.conv_skip(inputs)
        x_i = self.batch_norm_skip(x_i)
        x = self.add([x, x_i])
        
        return x
        
        

In [25]:
residual_layer = ResidualLayer(n_filter=1, kernel_size=1)


In [26]:
i = keras.Input((1, 64, 64, 3))


In [27]:
o = residual_layer(i)
o


<KerasTensor: shape=(None, 1, 64, 64, 1) dtype=float32 (created by layer 'residual')>

In [28]:
model = Model(inputs=i, outputs=o)


In [29]:
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 1, 64, 64, 3)]    0         
                                                                 
 residual (ResidualLayer)    (None, 1, 64, 64, 1)      30        
                                                                 
Total params: 30
Trainable params: 20
Non-trainable params: 10
_________________________________________________________________


In [31]:
ResidualLayer(np.ones((1, 2, 2, 3)))


### Losses

**Dice Loss**

In [19]:
from tf_seg.losses import dice_coef, dice_loss, DiceLoss


In [20]:
t = np.array([[1, 0, 1, 0, 0]], dtype=float)
p = np.array([[1, 0, 1, 0, 1], [1, 0, 1, 0, 0]], dtype=float)
i = 100000
p = np.random.choice(2, size=(i)).astype(float)
t = np.random.choice(2, size=(i)).astype(float)


In [21]:
dice_loss = DiceLoss()


In [22]:
dice_loss(t, p)


<tf.Tensor: shape=(), dtype=float64, numpy=0.5006293077604635>

### Metrics

In [23]:
%load_ext autoreload
%autoreload 2
from tensorflow.keras.metrics import BinaryAccuracy,binary_accuracy
from tensorflow.keras.metrics import MeanMetricWrapper
from tensorflow.keras.metrics import MeanIoU,Precision

import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
from tf_seg.metrics import DiceScore
from tf_seg.metrics import MeanMetricWrapper


In [25]:
dice_score = DiceScore(name="dice_score_spece")


In [26]:
t = np.array([[1, 0, 1, 0, 0]], dtype=float)
p = np.array([[1, 0, 1, 0, 1], [1, 0, 1, 0, 0]], dtype=float)
i = 100000
p = np.random.choice(2, size=(i)).astype(float)
t = np.random.choice(2, size=(i)).astype(float)


In [27]:
iou_score = MeanIoU(num_classes=2, name="mean_iou")


In [28]:
iou_score(t, p)


<tf.Tensor: shape=(), dtype=float32, numpy=0.3309198>

In [29]:
dice_score(t, p)


<tf.Tensor: shape=(), dtype=float32, numpy=0.49696812>

In [30]:
dice_score.result()


<tf.Tensor: shape=(), dtype=float32, numpy=0.49696812>

In [31]:
dice_score.get_weights()


[0.49696812, 1.0]

### Data 

In [2]:
%load_ext autoreload
%autoreload 2
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.utils import image_dataset_from_directory
import tensorflow as tf
#from tensorflow_addons.image import rotate
from glob import glob
import matplotlib.pyplot as plt
import albumentations as A


from tf_seg.data import DataLoader
from tf_seg.data import get_camvid_data_loader

import time

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
# train_image_paths = glob("./dataset_v1.0/train_image/*.jpg")
# train_annot_paths = glob("./dataset_v1.0/train_annot/*.jpg")

# camvid
train_image_paths = sorted(glob("./dataset/camvid/train/*.png"))
train_annot_paths = sorted(glob("./dataset/camvid/train_labels/*.png"))

assert len(train_image_paths) > 0 and len(train_annot_paths) > 0, f"No training images found  train image length {len(train_image_paths)} train annot length {len(train_annot_paths)}"


AssertionError: No training images found  train image length 0 train annot length 0

In [4]:
train_annot_paths[:3], train_image_paths[:3]


([], [])

In [4]:
import os
import urllib
import zipfile

In [5]:
url = "https://storage.googleapis.com/kaggle-data-sets/635428/1132317/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20221006%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20221006T152140Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=2c7e207916903eafc1e58493d3b54304b271a1e6699796219be1de5e7b4f919da977d244432b3b1b0c4539e3c732de920f572028bbb923cae8b12a87f03acc6d4dbf0d6778dd62acaf4a54e39112f1c573316666128591073b34756c441cbc95244ec86df3c69f5ab0eee10ea744776a95f66a2e4e0e6ed01050529c3baa48886fbdbd1495e6b9f392adb9ea1f5d02ed5b58bacf73d8055f4795c914766a8ee85615a575e73fd628baddab50b7b205e8eba31ec5ab6a91322b818ed408bb09b55ad384098c58f988c4c385106793889ebb1bfc1fca234c2caecf35f5b7861f650c2d14ec90ebd7f49c9a2d300b40fa95ba6ce552fcf2eb874b164934ec0c15c4"

In [6]:
# urllib.request.urlretrieve(url, filename="deneme.zip")

In [ ]:
def download_data(data_name: str):
    """ Downloads the specified dataset.
    Returns
    -------
    """
    downloader = getattr(dataset, f"download_{data_name}_dataset")
    downloader()
    # os.remove("deneme.zip")

In [5]:
from tf_seg.data.dataset import download_data

In [6]:
download_data("camvid")

In [6]:
# Road,128, 64, 128
# RoadShoulder,128, 128, 192
# Sidewalk,0, 0, 192
# SignSymbol,192, 128, 128
# Sky,128, 128, 128

CLASSES = ["Road", "Sky"]
palette = [(128, 64, 128), (128, 128, 128)]


In [7]:
#data_loader = DataLoader(train_image_paths, train_annot_paths, image_size=(512, 512), output_type=(tf.float32, tf.float32),one_hot_encoding=True,channels = (3,3),palette=palette,background_adding=True)

#dataset = data_loader.load_data(batch_size=12,shuffle=True)

In [8]:
# for (i,m)  in dataset.take(3):
#     #plt.imshow(i.numpy().astype(int))
#     plt.subplot(1,2,1)
#     plt.imshow(tf.cast(i,tf.uint8))
#     plt.subplot(1,2,2)
#     plt.imshow(m)
#     plt.show()


#### Tensorflow Dataset

In [1]:
import tensorflow as tf

2022-10-03 20:46:33.120921: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-03 20:46:33.248106: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-10-03 20:46:33.252986: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-03 20:46:33.252999: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if yo

In [5]:
import tensorflow_datasets as tfds

In [ ]:
tfds.load("oxford_iiit_pet:3.*.*")

#### albumentations

In [38]:
IM_SIZE = 512
BATCH_SIZE = 12

transforms = A.Compose(
    [
        A.Resize(IM_SIZE, IM_SIZE),
        A.OneOf(
            [
                A.HorizontalFlip(),
                A.VerticalFlip(),
            ],
            p=0.3,
        ),
        A.RandomRotate90(),
        # A.RandomGridShuffle(grid=(3, 3), always_apply=False, p=0.5),
        A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, always_apply=False, p=0.5),
        # A.Cutout(num_holes=8, max_h_size=8, max_w_size=8, fill_value=0, always_apply=False, p=0.5),
        A.Sharpen(alpha=(0.2, 0.5), lightness=(0.5, 1.0), always_apply=False, p=0.5),
    ]
)


In [39]:
import albumentations as A


In [40]:
A.RandomBrightnessContrast??

Init signature:
A.RandomBrightnessContrast(
    brightness_limit=0.2,
    contrast_limit=0.2,
    brightness_by_max=True,
    always_apply=False,
    p=0.5,
)
Source:        
class RandomBrightnessContrast(ImageOnlyTransform):
    """Randomly change brightness and contrast of the input image.

    Args:
        brightness_limit ((float, float) or float): factor range for changing brightness.
            If limit is a single float, the range will be (-limit, limit). Default: (-0.2, 0.2).
        contrast_limit ((float, float) or float): factor range for changing contrast.
            If limit is a single float, the range will be (-limit, limit). Default: (-0.2, 0.2).
        brightness_by_max (Boolean): If True adjust contrast by image dtype maximum,
            else adjust contrast by image mean.
        p (float): probability of applying the transform. Default: 0.5.

    Targets:
        image

    Image types:
        uint8, float32
    """

    def __init__(
        self,
        br

In [41]:
def aug_albument(image, mask):
    data = {"image": image, "mask": mask}
    data = transforms(**data)
    image = data["image"]
    mask = data["mask"]
    # image = tf.cast(image/255., tf.float32)
    return image, mask


In [42]:
@tf.function
def process_data(image, mask):
    aug_img, aug_mask = tf.numpy_function(func=aug_albument, inp=[image, mask], Tout=[tf.uint8, tf.uint8])
    return aug_img, aug_mask


In [48]:
DataLoader?

Init signature:
DataLoader(
    image_paths: List[str],
    mask_paths: List[str],
    image_size: Tuple[int],
    batch_size: int,
    channels: Tuple[int],
    output_type: Tuple[tensorflow.python.framework.dtypes.DType],
    name: str = 'loader',
    normalizing: bool = True,
    extensions: Tuple[str] = None,
    one_hot_encoding: bool = False,
    palette: List[Tuple[int]] = None,
    background_adding: bool = False,
    seed: int = 48,
)
Docstring:     
A TensorFlow Dataset API based loader for semantic segmentation problems.

See Also
--------
- https://github.com/HasnainRaz/SemSegPipeline/blob/master/dataloader.py
Init docstring:
Initializes the data loader object

Parameters
----------
image_paths : List[str]
    List of paths of train images.
mask_paths : List[str]
    List of paths of train masks (segmentation masks)
image_size : Tuple[int]
    Tuple, the final height, width of the loaded images.
extensions : Tuple[str]
    Tuple, the extensions of the images.
channels : Tup

In [49]:
data_loader = DataLoader(
    train_image_paths, train_annot_paths, image_size=(512, 512), batch_size=1,output_type=(tf.uint8, tf.float32), one_hot_encoding=True, channels=(3, 3), palette=palette, background_adding=True
)


In [50]:
train_dataset = data_loader.load_data(batch_size=20, shuffle=True, transform_func=process_data)


In [51]:
def t():
    for (i, m) in train_dataset.take(100):
        pass
        # print(i.shape)


In [53]:
ti = time.time()
t()
print(time.time() - ti)


2022-09-21 10:32:31.094677: W tensorflow/core/framework/op_kernel.cc:1768] INVALID_ARGUMENT: ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: <tf.Tensor: shape=(512, 512, 3), dtype=float32, numpy=
array([[[ 1.8914273 ,  1.8914273 ,  1.8771276 ],
        [ 1.8914273 ,  1.8914273 ,  1.8914273 ],
        [ 1.8914273 ,  1.8914273 ,  1.8914273 ],
        ...,
        [-0.6825015 , -0.61100346, -0.5681047 ],
        [-0.63960266, -0.55380505, -0.5109062 ],
        [-0.63960266, -0.55380505, -0.52520585]],

       [[ 1.8914273 ,  1.8914273 ,  1.8914273 ],
        [ 1.8056296 ,  1.8056296 ,  1.8342288 ],
        [ 1.7770303 ,  1.7627308 ,  1.8199292 ],
        ...,
        [-0.6825015 , -0.5967039 , -0.5681047 ],
        [-0.6539023 , -0.58240426, -0.52520585],
        [-0.63960266, -0.55380505, -0.5109062 ]],

       [[ 1.7627308 ,  1.7341316 ,  1.8485284 ],
        [ 1.3766415 ,  1.3194431 ,  1.6197348 ],
        [ 1.6197348 ,  1.5911355 ,  1.8056296 ],
    

InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: <tf.Tensor: shape=(512, 512, 3), dtype=float32, numpy=
array([[[-3.3483422e-01, -3.3483422e-01, -3.0699056e-01],
        [-4.1836518e-01, -4.3228701e-01, -4.0444335e-01],
        [-4.6013066e-01, -4.6013066e-01, -4.0444335e-01],
        ...,
        [-9.0562916e-01, -8.9170730e-01, -8.9170730e-01],
        [-8.7778550e-01, -8.6386365e-01, -8.6386365e-01],
        [-8.6386365e-01, -8.4994185e-01, -8.4994185e-01]],

       [[-9.8163158e-02, -9.8163158e-02, -9.8163158e-02],
        [-2.9306874e-01, -3.0699056e-01, -3.0699056e-01],
        [-4.6013066e-01, -4.6013066e-01, -4.3228701e-01],
        ...,
        [-9.3347281e-01, -9.1955096e-01, -9.1955096e-01],
        [-8.9170730e-01, -8.7778550e-01, -8.7778550e-01],
        [-8.7778550e-01, -8.6386365e-01, -8.6386365e-01]],

       [[-7.1036670e-04, -7.1036670e-04, -2.8554022e-02],
        [-2.8554022e-02, -2.8554022e-02, -5.6397676e-02],
        [-3.3483422e-01, -3.3483422e-01, -3.6267787e-01],
        ...,
        [-8.7778550e-01, -8.6386365e-01, -8.6386365e-01],
        [-8.4994185e-01, -8.3601999e-01, -8.3601999e-01],
        [-8.9170730e-01, -8.6386365e-01, -8.6386365e-01]],

       ...,

       [[-7.3856723e-01, -6.8287992e-01, -6.4111441e-01],
        [-7.1072358e-01, -6.5503627e-01, -6.1327076e-01],
        [-6.6895807e-01, -6.1327076e-01, -5.7150531e-01],
        ...,
        [-2.2345960e-01, -2.7914691e-01, -3.3483422e-01],
        [-1.8169412e-01, -2.5130326e-01, -2.7914691e-01],
        [-1.6777229e-01, -2.5130326e-01, -2.7914691e-01]],

       [[-8.2209820e-01, -7.5248903e-01, -7.2464538e-01],
        [-7.8033268e-01, -7.2464538e-01, -6.8287992e-01],
        [-7.2464538e-01, -6.6895807e-01, -6.2719262e-01],
        ...,
        [-1.8169412e-01, -2.2345960e-01, -3.3483422e-01],
        [-2.7914691e-01, -3.3483422e-01, -4.1836518e-01],
        [-1.3992864e-01, -2.0953777e-01, -2.7914691e-01]],

       [[-8.0817634e-01, -7.5248903e-01, -7.1072358e-01],
        [-7.9425454e-01, -7.3856723e-01, -6.9680172e-01],
        [-7.5248903e-01, -6.8287992e-01, -6.6895807e-01],
        ...,
        [-7.1036670e-04, -4.2475849e-02, -1.5385047e-01],
        [-2.5130326e-01, -2.9306874e-01, -4.0444335e-01],
        [-2.5130326e-01, -3.2091239e-01, -4.1836518e-01]]], dtype=float32)>
Traceback (most recent call last):

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 163, in _call
    outputs = [

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 164, in <listcomp>
    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 131, in _convert
    return ops.convert_to_tensor(value, dtype=dtype)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py", line 183, in wrapped
    return func(*args, **kwargs)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1599, in convert_to_tensor
    raise ValueError(

ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: <tf.Tensor: shape=(512, 512, 3), dtype=float32, numpy=
array([[[-3.3483422e-01, -3.3483422e-01, -3.0699056e-01],
        [-4.1836518e-01, -4.3228701e-01, -4.0444335e-01],
        [-4.6013066e-01, -4.6013066e-01, -4.0444335e-01],
        ...,
        [-9.0562916e-01, -8.9170730e-01, -8.9170730e-01],
        [-8.7778550e-01, -8.6386365e-01, -8.6386365e-01],
        [-8.6386365e-01, -8.4994185e-01, -8.4994185e-01]],

       [[-9.8163158e-02, -9.8163158e-02, -9.8163158e-02],
        [-2.9306874e-01, -3.0699056e-01, -3.0699056e-01],
        [-4.6013066e-01, -4.6013066e-01, -4.3228701e-01],
        ...,
        [-9.3347281e-01, -9.1955096e-01, -9.1955096e-01],
        [-8.9170730e-01, -8.7778550e-01, -8.7778550e-01],
        [-8.7778550e-01, -8.6386365e-01, -8.6386365e-01]],

       [[-7.1036670e-04, -7.1036670e-04, -2.8554022e-02],
        [-2.8554022e-02, -2.8554022e-02, -5.6397676e-02],
        [-3.3483422e-01, -3.3483422e-01, -3.6267787e-01],
        ...,
        [-8.7778550e-01, -8.6386365e-01, -8.6386365e-01],
        [-8.4994185e-01, -8.3601999e-01, -8.3601999e-01],
        [-8.9170730e-01, -8.6386365e-01, -8.6386365e-01]],

       ...,

       [[-7.3856723e-01, -6.8287992e-01, -6.4111441e-01],
        [-7.1072358e-01, -6.5503627e-01, -6.1327076e-01],
        [-6.6895807e-01, -6.1327076e-01, -5.7150531e-01],
        ...,
        [-2.2345960e-01, -2.7914691e-01, -3.3483422e-01],
        [-1.8169412e-01, -2.5130326e-01, -2.7914691e-01],
        [-1.6777229e-01, -2.5130326e-01, -2.7914691e-01]],

       [[-8.2209820e-01, -7.5248903e-01, -7.2464538e-01],
        [-7.8033268e-01, -7.2464538e-01, -6.8287992e-01],
        [-7.2464538e-01, -6.6895807e-01, -6.2719262e-01],
        ...,
        [-1.8169412e-01, -2.2345960e-01, -3.3483422e-01],
        [-2.7914691e-01, -3.3483422e-01, -4.1836518e-01],
        [-1.3992864e-01, -2.0953777e-01, -2.7914691e-01]],

       [[-8.0817634e-01, -7.5248903e-01, -7.1072358e-01],
        [-7.9425454e-01, -7.3856723e-01, -6.9680172e-01],
        [-7.5248903e-01, -6.8287992e-01, -6.6895807e-01],
        ...,
        [-7.1036670e-04, -4.2475849e-02, -1.5385047e-01],
        [-2.5130326e-01, -2.9306874e-01, -4.0444335e-01],
        [-2.5130326e-01, -3.2091239e-01, -4.1836518e-01]]], dtype=float32)>


	 [[{{function_node __inference__map_fucntion_3787}}{{node EagerPyFunc}}]] [Op:IteratorGetNext]

In [ ]:
ti = time.time()
t()
print(time.time() - ti)


In [54]:
%%timeit
train_dataset.take(1)

102 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [55]:
i, m = train_dataset.take(1)

2022-09-21 10:55:33.607632: W tensorflow/core/framework/op_kernel.cc:1768] INVALID_ARGUMENT: ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: <tf.Tensor: shape=(512, 512, 3), dtype=float32, numpy=
array([[[ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        [ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        [ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        ...,
        [ 0.83722067,  1.2784507 ,  1.2784507 ],
        [ 0.95647204,  1.2784507 ,  1.2784507 ],
        [ 0.95647204,  1.2784507 ,  1.2784507 ]],

       [[ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        [ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        [ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        ...,
        [ 0.86107093,  1.2784507 ,  1.2784507 ],
        [ 0.9087715 ,  1.2784507 ,  1.2784507 ],
        [ 0.8491458 ,  1.2784507 ,  1.2784507 ]],

       [[ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        [ 1.2784507 ,  1.2784507 ,  1.2784507 ],
        [ 1.2784507 ,  1.2784507 ,  1.2784507 ],
    

InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: <tf.Tensor: shape=(512, 512, 3), dtype=float32, numpy=
array([[[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ]],

       ...,

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [ 1.651318  ,  2.0487971 ,  2.7714868 ],
        [ 1.651318  ,  1.5429145 ,  0.7298887 ],
        [ 1.651318  ,  1.8139231 ,  2.2114024 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [ 1.651318  ,  2.0849316 ,  2.6992178 ],
        [ 1.651318  ,  1.3803093 ,  0.49501452],
        [ 1.651318  ,  1.8500576 ,  1.8319904 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [ 1.651318  ,  2.121066  ,  2.7714868 ],
        [ 1.651318  ,  1.2899731 ,  0.38661107],
        [ 1.651318  ,  1.8861921 ,  2.03073   ]]], dtype=float32)>
Traceback (most recent call last):

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 163, in _call
    outputs = [

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 164, in <listcomp>
    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 131, in _convert
    return ops.convert_to_tensor(value, dtype=dtype)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py", line 183, in wrapped
    return func(*args, **kwargs)

  File "/home/yesilyurt/miniconda3/envs/tf_seg/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1599, in convert_to_tensor
    raise ValueError(

ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: <tf.Tensor: shape=(512, 512, 3), dtype=float32, numpy=
array([[[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ]],

       ...,

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [ 1.651318  ,  2.0487971 ,  2.7714868 ],
        [ 1.651318  ,  1.5429145 ,  0.7298887 ],
        [ 1.651318  ,  1.8139231 ,  2.2114024 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [ 1.651318  ,  2.0849316 ,  2.6992178 ],
        [ 1.651318  ,  1.3803093 ,  0.49501452],
        [ 1.651318  ,  1.8500576 ,  1.8319904 ]],

       [[-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        [-0.5348182 , -0.5348182 , -0.5348182 ],
        ...,
        [ 1.651318  ,  2.121066  ,  2.7714868 ],
        [ 1.651318  ,  1.2899731 ,  0.38661107],
        [ 1.651318  ,  1.8861921 ,  2.03073   ]]], dtype=float32)>


	 [[{{function_node __inference__map_fucntion_3787}}{{node EagerPyFunc}}]] [Op:IteratorGetNext]

#### Dataset

In [ ]:
import requests

**Camvid**

In [ ]:
import os
import sys
import tarfile
import time


source = "http://web4.cs.ucl.ac.uk/staff/g.brostow/MotionSegRecData/files/701_StillsRaw_full.zip"
target = '701_StillsRaw_full.zip'


In [ ]:
def reporthook(count, block_size, total_size):
    global start_time
    if count == 0:
        start_time = time.time()
        return
    duration = time.time() - start_time
    progress_size = int(count * block_size)
    speed = progress_size / (1024.**2 * duration)
    percent = count * block_size * 100. / total_size
    sys.stdout.write("\r%d%% | %d MB | %.2f MB/s | %d sec elapsed" %
                    (percent, progress_size / (1024.**2), speed, duration))
    sys.stdout.flush()


if not os.path.isdir('701_StillsRaw') and not os.path.isfile('701_StillsRaw_full.zip'):
    
    if (sys.version_info < (3, 0)):
        import urllib
        urllib.urlretrieve(source, target, reporthook)
    
    else:
        import urllib.request
        urllib.request.urlretrieve(source, target, reporthook)

In [ ]:
urllib.request.urlretrieve(source, target,lambda c,b,t: print(t))

### Aug

In [ ]:
%load_ext autoreload
%autoreload 2


import tensorflow as tf

import numpy as np
import matplotlib.pyplot as plt

#from tensorflow.keras.utils import image_dataset_from_directory
#from tensorflow.keras.preprocessing.image import load_img, img_to_array
#from tensorflow_addons.image import rotate
#from glob import glob
#from tf_seg.data import DataLoader

from tf_seg.data.aug import jax_random_crop

In [ ]:
image_path = "dataset/camvid/train/0001TP_009210.png"
mask_path = "dataset/camvid/train_labels/0001TP_009210_L.png"


In [ ]:
image_content = tf.io.read_file(image_path)
mask_content = tf.io.read_file(mask_path)

image = tf.image.decode_png(image_content, channels=3)
mask = tf.image.decode_png(mask_content, channels=3)


In [ ]:
i, m = image.numpy(), mask.numpy()


In [ ]:
%%timeit
jax_random_crop(i,m)

In [ ]:
plt.figure(figsize=(10, 10))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.subplot(1, 2, 2)
plt.imshow(mask)


### Config

In [ ]:
%load_ext autoreload
%autoreload 2


import tensorflow as tf

import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path
from typing import List, Optional, Union
from warnings import warn

import os 
from omegaconf import DictConfig, ListConfig, OmegaConf

from tf_seg.config import get_config
from tf_seg.models import get_model_builder

from tf_seg.data import get_camvid_data_loader
from tf_seg.data import get_data_loader    

#from tf_seg.config import CONFIG_LOAD_STYLE_LIB,CONFIG_FILE_EXTENSION,CONFIG_STORE_PATH
#from tf_seq.config.

In [ ]:
# load config function

# parameter
config_name = "test"
config_path = None

# constant parameters get from constant.py
# CONFIG_STORE_PATH = "./config"
# CONFIG_FILE_EXTENSION = ".yaml"


In [ ]:
config = get_config(config_name, config_path)

#### get_model function


In [ ]:
model_builder = get_model_builder(config)

In [ ]:
from tf_seg.models import model_lib

In [ ]:
# necessary imports
from tensorflow.keras.models import Model
from omegaconf import DictConfig, ListConfig


def pascal_case_to_snake_case(s:str)->str:
    """Convert class name to snake case name."""
    return "".join(["_"+i.lower() if i.isupper() else i for i in s]).lstrip("_")

In [ ]:
def get_model_builder(config:Union[DictConfig, ListConfig])->Model:
    """Get keras model from config file"""
    class_name = pascal_case_to_snake_case(config.model.class_name)
    model = model_lib[class_name]

    model_config = config.model.copy()    
    model_config.pop("class_name")
    
    return model(**model_config) 

#### get_data function

In [ ]:
loaders =get_data_loader(config,train_data=True,val_data=True,test_data=False)

In [ ]:
dataset = loaders[0].load_data(batch_size=1)

In [ ]:
for i in dataset.take(1):
    plt.imshow(tf.squeeze(i[1]))
    break

#### get_aug function

In [ ]:
from tf_seg.transformers import get_transformer
from tf_seg.utils import AlbumentatiosWrapper
import importlib

In [ ]:
config = get_config(config_name, config_path)
aug_config = config.augmentation
aug_config

In [ ]:
lib = get_transformer(config)

In [ ]:
aug_config = config.augmentation

In [ ]:
lib = get_transformer(config)
lib

#### get_config function

In [ ]:
def get_config(
    config_filename: Optional[str] = None, config_path: Optional[Union[Path, str]] = None, config_file_extension: Optional[str] = CONFIG_FILE_EXTENSION, config_store_path: "str" = CONFIG_STORE_PATH
) -> Union[DictConfig, ListConfig]:

    """
    Get configurable parameters from config file.

    Parameters
    ----------
    config_filename : str, optional
        Name of the config file. The default is None.
    config_path : Union[Path, str], optional
        Path of the config file. The default is None.
    config_file_extension : str, optional
        File extension of the config file. The default is ".yaml".
    config_store_path : str
        Path of the config store. The default is "./config".

    Returns
    -------
    config : Union[DictConfig, ListConfig]
        Configurable parameters.

    """
    assert os.path.isdir(config_store_path), f"{config_store_path} is not a directory"

    if config_path is None:
        config_path = Path(f"{config_store_path}/{config_name}{config_file_extension}")

    config = OmegaConf.load(config_path)

    return config


In [ ]:
config = get_config(config_name)
config


In [ ]:
def check_base_config_exist(config: Union[DictConfig, ListConfig]) -> bool:
    """check if base config exist in config file"""

    if "base" in config.keys():
        if config["base"] is None:
            return False
        else:
            return True
    else:
        return False


def load_yaml_style_config(yaml_path: str) -> Union[DictConfig, ListConfig]:
    """load config from yaml file"""
    assert os.path.isfile(yaml_path), f"{yaml_path} is not a file"
    config = OmegaConf.load(yaml_path)
    return config


def load_module_style_config(module_path: str) -> Union[DictConfig, ListConfig]:
    """load config from python module"""
    raise NotImplementedError("load_mdule_style_config is not implemented")


def load_base_config(config):
    """load base config from base parameter"""

    # find file extension
    load_style = os.path.splitext(config["base"])[1]

    print("load style :", load_style)

    if load_style == ".py":  # module style
        raise NotImplementedError("load_style is not implemented")

    elif load_style == ".yaml" or load_style == ".yml":
        return load_yaml_style_config(config["base"])

    else:
        raise ValueError("load_style is not valid")


In [ ]:
def extact_config(config: Union[DictConfig, ListConfig]) -> Union[DictConfig, ListConfig]:
    """"Extract parent base config and merge with child configs"""

    first_config_keys = list(config.keys())
    buffer_config_dict = {}
    f_config = config.copy()

    for first_k in first_config_keys:

        sub_config = f_config[first_k]

        if check_base_config_exist(sub_config):
            buffer_config = load_base_config(sub_config)
            sub_config.pop("base")
            buffer_config.merge_with(sub_config)
            sub_config = buffer_config

        else:
            if "base" in sub_config.keys():
                sub_config.pop("base")

        f_config[first_k] = sub_config

    return f_config


In [ ]:
f_config["augmentation"]

In [ ]:
sub_config

In [ ]:
buffer_config

In [ ]:
sub_config.pop("base")

In [ ]:
for b_k in b.keys():
    


In [ ]:
b.merge_with(sub_config)

### Backbone

In [ ]:
%load_ext autoreload
%autoreload 2


import sys
import numpy as np

import tensorflow as tf
from tensorflow import keras


# from tensorflow.keras import initializers
# from tensorflow.keras.layers import Conv2D,Conv1D
# from tensorflow.keras.layers import BatchNormalization
# from tensorflow.keras.layers import Layer
# from tensorflow.keras.losses import Loss
# from tensorflow.keras import Model
# from tensorflow.keras import initializers

from tf_seg.models import Unet,ResUnet
from tf_seg.backbones import get_backbone 
from tensorflow.keras.layers import Input
from tensorflow.python.keras.engine import keras_tensor
from tensorflow.keras.layers import Conv2D,Conv2DTranspose,Concatenate
from tensorflow.keras.models import Model


**Done Work**

#### Unet

In [ ]:
backbone = None #"EfficientNetB1"#"ResNet50"

n_filters = [8, 16, 32, 64, 128,256]#, 512, 1024]
model=Unet(backbone=backbone,n_filters=n_filters,input_shape=(256, 256,3)).build_model()

out = model(np.ones((1,256,256,3)))
keras.utils.plot_model(model,show_shapes=True)

#### ResUnet

##### Workspace

In [ ]:

sys.path.append("appendix/keras-unet-collection")

In [ ]:
from keras_unet_collection import models

In [ ]:
model = models.unet_2d((1024, 1024, 3), [16, 32,312], n_labels=2,backbone="EfficientNetB1")
#model = models.unet_2d((1024, 1024, 3), [64, 128, 256, 512, 1024], n_labels=2)

In [ ]:
keras.utils.plot_model(model,show_shapes=True)

In [ ]:
input_tensor = Input((1024,1024,3))
#backbone = get_backbone("ResNet50","imagenet",input_tensor,depth=4,freeze_backbone=True,freeze_batch_norm=False)
backbone = get_backbone("ResNet50V2","imagenet",input_tensor,depth=5,freeze_backbone=True,freeze_batch_norm=False)
backbone(input_tensor) 

In [ ]:
#model= Unet(backbone="ResNet50",n_filters=[16,32,64]).build_model()
model= Unet(backbone=None,n_filters=[32,64,128,256,512,1024]).build_model()


connection_list = model[0]
decode_n_filters= model[1]
inputs = model[2]
bridge = model[3]

final_activation = "relu"
n_classes = 3

In [ ]:
backbone = "ResNet50"
n_filters = [32,64,128,256,512]
#encoder_output= Unet(backbone=None,n_filters=[32,64,128,256,512]).build_model()
encoder_output= Unet(backbone=backbone,n_filters=n_filters).build_model()

inputs = encoder_output[0]
bridge = encoder_output[-1]
connection_list = encoder_output[1:-1][::-1]
inputs,bridge,connection_list

In [ ]:
# if backbone is None:
#     decoder_n_filters = n_filters[:-1][::-1]
decoder_n_filters = n_filters[:-1][::-1]
decoder_n_filters

In [ ]:
d = bridge

for n,c in enumerate(connection_list):

    print("connection :",c.shape,n)
    d=Conv2DTranspose(decoder_n_filters[n], (3, 3), padding="same", strides=(2, 2))(d)
    print(d.shape)
    d = Concatenate()([d,c])
    print("after concat :",d.shape)
    d = Unet()._conv_block(d,decoder_n_filters[n],pool=False)

print("last shape :",d.shape)

In [ ]:
depth = len(connection_list)

if len(decoder_n_filters)>depth:
    n_remain_block = len(decoder_n_filters) - depth
    print(decoder_n_filters[-1*n_remain_block:])

    remain_decoder_n_filter=decoder_n_filters[-1*n_remain_block:]
    for fltr in remain_decoder_n_filter:
        print(fltr)
        d=Conv2DTranspose(fltr, (3, 3), padding="same", strides=(2, 2))(d)
        d = Unet()._conv_block(d,fltr,pool=False)
    
print("last shape :", d.shape)


In [ ]:
# if not backbone is None:
# not bigger n_filters 6
#  not smaller n_filters 3

### Trainer

In [ ]:
from typing import Union, Optional, List
from omegaconf import DictConfig, ListConfig
from tensorflow.keras import Model
from tensorflow.data import Dataset
from tensorflow.keras.callbacks import Callback

In [ ]:

class Trainer:
    "Trainer class for training a model"

    def __init__(self, config: Union[DictConfig, ListConfig], model: Model,
                 train_data: Dataset, val_data: Optional[Dataset] = None,
                 callbacks: Optional[List[Callback]] = None) -> None:
        """


        Parameters
        ----------
        config: Union[DictConfig, ListConfig]
            Configuration for training
        model: tf.keras.Model
            Model to be trained
        train_data: tf.data.Dataset
            Dataset for training
        val_data: tf.data.Dataset,default: None
            Dataset for validation
        callbacks: tf.keras.callbacks.Callback,default: None
            keras Callbacks for training

        """
        self.config = config
        self.model:Model = model
        self.train_data = train_data
        self.val_data = val_data
        self.callbacks = callbacks

        self._check_params()

    def _check_params(self) -> None:
        pass

    def train(self):
        "Train tf keras model"
        
        self.model.fit(self.train_data,
                       epochs=self.config.epochs,
                       callbacks=self.callbacks,
                       validation_data=self.val_data)

    def evaluate(self):
        if self.val_data: 
            self.model.evaluate(self.val_data)
        else:
            raise ValueError("Validation data is not provided")
            
    def save(self, filename):
        self.model.save(filename)

    def test(self, data):
        self.model.evaluate(data)

### Callbacks

```python
class CustomCallback(keras.callbacks.Callback):
    def on_train_begin(self, logs=None):
        keys = list(logs.keys())
        print("Starting training; got log keys: {}".format(keys))

    def on_train_end(self, logs=None):
        keys = list(logs.keys())
        print("Stop training; got log keys: {}".format(keys))

    def on_epoch_begin(self, epoch, logs=None):
        keys = list(logs.keys())
        print("Start epoch {} of training; got log keys: {}".format(epoch, keys))

    def on_epoch_end(self, epoch, logs=None):
        keys = list(logs.keys())
        print("End epoch {} of training; got log keys: {}".format(epoch, keys))

    def on_test_begin(self, logs=None):
        keys = list(logs.keys())
        print("Start testing; got log keys: {}".format(keys))

    def on_test_end(self, logs=None):
        keys = list(logs.keys())
        print("Stop testing; got log keys: {}".format(keys))

    def on_predict_begin(self, logs=None):
        keys = list(logs.keys())
        print("Start predicting; got log keys: {}".format(keys))

    def on_predict_end(self, logs=None):
        keys = list(logs.keys())
        print("Stop predicting; got log keys: {}".format(keys))

    def on_train_batch_begin(self, batch, logs=None):
        keys = list(logs.keys())
        print("...Training: start of batch {}; got log keys: {}".format(batch, keys))

    def on_train_batch_end(self, batch, logs=None):
        keys = list(logs.keys())
        print("...Training: end of batch {}; got log keys: {}".format(batch, keys))

    def on_test_batch_begin(self, batch, logs=None):
        keys = list(logs.keys())
        print("...Evaluating: start of batch {}; got log keys: {}".format(batch, keys))

    def on_test_batch_end(self, batch, logs=None):
        keys = list(logs.keys())
        print("...Evaluating: end of batch {}; got log keys: {}".format(batch, keys))

    def on_predict_batch_begin(self, batch, logs=None):
        keys = list(logs.keys())
        print("...Predicting: start of batch {}; got log keys: {}".format(batch, keys))

    def on_predict_batch_end(self, batch, logs=None):
        keys = list(logs.keys())
        print("...Predicting: end of batch {}; got log keys: {}".format(batch, keys))


```

In [ ]:
%load_ext autoreload 
%autoreload 2
import time

import tensorflow as tf
from tensorflow import keras

import numpy as np

from tensorflow.keras.callbacks import LearningRateScheduler, ReduceLROnPlateau,Callback
from tensorflow.keras.optimizers.schedules import PolynomialDecay,PiecewiseConstantDecay
from tf_seg.utils import  snake_case_to_pascal_case
from tf_seg.callbacks import get_callbacks



In [ ]:
tf.random.set_seed(42)
np.random.seed(42)

In [ ]:
# parameter
config_name = "test"
config_path = None
config = get_config(config_name, config_path)

In [ ]:
config.callbacks

In [ ]:
model.set_weights??

In [ ]:
get_callbacks(config.callbacks)

In [ ]:
config.callbacks

In [ ]:
a = {"a":12}
b = {"b":12}

In [ ]:
np.less(1,2)

In [ ]:
c_config  = config.callbacks

In [ ]:
for i in c_config.keys():
    print(snake_case_to_pascal_case(i))

In [ ]:
size = 100
x1 = np.random.randint(1,10,(size,10,1))
y1 = x1.max(axis=1) #+ np.random.rand(size)
x1 = np.concatenate((x1,np.ones((size,1,1))),axis=1)


x2 = np.random.randint(1,10,(size,10,1))
y2 = x2.min(axis=1) #+ np.random.rand(size)
x2 = np.concatenate((x2,np.zeros((size,1,1))),axis=1)

x = np.concatenate((x1,x2))
y = np.concatenate((y1,y2))

In [ ]:
def get_model(input_dim):
    model = keras.Sequential()
    model.add(keras.layers.Dense(1, input_dim=input_dim,use_bias=False))
    model.compile(
        optimizer=keras.optimizers.Nadam(learning_rate=0.001),
        loss=tf.keras.losses.mae,
        metrics=["mae"],
    )
    return model


model = get_model(input_dim=11)

In [ ]:
# class CustomCallbacks(keras.callbacks.Callback):
#     def __init__(self):
#         super().__init__()
#         self.epoch_level = 10
#     def on_train_begin(self,logs=None):
#         print(self.model)
#         #print(logs.keys())
            
#     def on_epoch_end(self,epoch,logs=None):
#         #print("training epoch end:",logs.keys())
#         print(self.dataset)
#         if epoch% self.epoch_level==0:
#             print(f"Epoch : {epoch} , loss : {logs}")
#     # def on_batch_end(self,batch,logs=None):
#     #     print("     => training batch end:",logs.keys())
class MeasureTotalTime(tf.keras.callbacks.Callback):
    def on_train_begin(self, logs=None):
        print(self.model)
        self.start_time = time.time()

    def on_train_end(self, logs=None):
        self.total_time = time.time() - self.start_time
        print("Total training time: %s" % self.total_time)


class UpdateBestWeights(Callback):
    def __init__(self, metric_name: str, mode:str):
        """
        Update best weights on end of training

        Parameters
        ----------
        metric_name : str
            Name of the metric to use for determining the best weights
        mode : str
            One of {min, max}
        """
        
        super().__init__()
       
        self.metric_name = metric_name
        self.best_weights = None
        self.best_metric = None

        if mode == 'max':
            self.monitor_op = np.greater
            self.best_metric = -np.Inf
        elif mode == 'min':
            self.monitor_op = np.less
            self.best_metric = np.Inf
        else:
            raise ValueError('Mode {} not understood'.format(mode))
        
    def on_epoch_end(self, epoch, logs=None):
        metric = logs[self.metric_name]
        if self.monitor_op(metric, self.best_metric):
            self.best_metric = metric
            self.best_weights = self.model.get_weights()

    def on_train_end(self, logs=None):       
        self.model.set_weights(self.best_weights)
     


update_model = UpdateBestWeights(metric_name='val_loss',mode='min')
tl_tm = MeasureTotalTime() 
lr = LearningRateScheduler(PolynomialDecay(0.9,100,power=1),verbose=1)

In [ ]:
model.fit(x, y,validation_data=(x,y), epochs=10,batch_size=120,callbacks=[tl_tm,update_model],verbose=1)

In [ ]:
tf.keras.losses.mae(y.reshape(-1), model.predict(x).reshape(-1))

In [ ]:
model.evaluate(x,y,batch_size=32)

### Deploy